version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todo
    restart: always
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
