CREATE TABLE public.tb_task (
	user_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	finished_date timestamp(6) NULL,
	started_date timestamp(6) NULL,
	status bool NULL,
	title varchar(255) NULL,
	person_id int4 NULL,
	CONSTRAINT tb_task_pkey PRIMARY KEY (user_id)
);

CREATE TABLE public.tb_person (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_birth timestamp(6) NOT NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	CONSTRAINT tb_person_pkey PRIMARY KEY (id)
);